language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5

install:
  - pip install cython numpy
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace

script: 
- nosetests -s -v